### ISSUE TITLE
加载到100%，就不动了

### ISSUE THREAD

**Issue by lanlianhua99** [NOTF-API/NOTF-API.github.io#1]

**Comment by NOTF-API** [comment]
应该是github的网速问题，你试试https://notf-api.github.io/
里面的入口一，这个网站在半夜维护

**Comment by NOTF-API** [comment]
我这里从未遇到这个问题，除非修改游戏index.3786c.js时把代码改错了

**Comment by lanlianhua99** [comment]
> 我这里有遇到过这个问题，可以修改游戏索引.3786c.js 时把代码改错了
这样呀,我的意思是本地的入口一和二打不开

**Comment by lanlianhua99** [comment]
> > 我这里有遇到过这个问题，可以修改游戏索引.3786c.js 时代码改错了
> > 这样呀，我的英文是本地的入口一和二打不开,可付费吗

**Comment by NOTF-API** [comment]
啊不好意思啊，这是我的个人io仓库，这个地址是写死的，请问你是克隆了这个仓库吗

**Comment by lanlianhua99** [comment]
> 啊不好意思啊，这是我的个人仓库，这个地址是写死的，请问你是克隆了这个仓库吗

嗯,下载到本地了

**Comment by NOTF-API** [comment]
如果你的Live server端口是5500，你需要把这个入口二地址改成
https://localhost:5500/www.mutegame.com/www.mutegame.com/170/index.html

**Comment by lanlianhua99** [comment]
还是不行呀,哥们,报跨域的错误并且找不到相关的资源.你能不能加个好友,qq2082876261
